eureka:
  instance:
    instance-id: ProductService-instance
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
    port: 8180

spring:
    application:
      name: ProductService







